### ISSUE TITLE
Cannot set options

### ISSUE THREAD

**Issue by skbakker** [zerodois/vue-snack#2]
Hey,

When I try to configure the options and click a button where I've set my $snack action on, it doesn't show the snackbar. When I don't configure the options, It works as normal.

```
Vue.use(VueSnackbar, {
    // Possible values: 'top', 'top-left', 'top-right', 'bottom', 'bottom-left'
    // default 'bottom'
    position: 'top',
    // default 7500
    time: 7500,
    // default false
    close: true,
    methods: [],
});
```

I don't get errors while compiling or in my console.

**Comment by zerodois** [comment]
Hey, can you show me the code where is happening?
