### ISSUE TITLE
Documentation is incorrect

### ISSUE THREAD

**Issue by agnivade** [zerodois/vue-snack#4]
There are a couple of issues in the README

In the https://github.com/zerodois/vue-snack#install section:

- `options` should not be defined. It should be  `Vue.use(VueSnackbar, {position: 'bottom-right', time: 3000})`
- reference to the css file is not there. We should also import - `import 'vue-snack/dist/vue-snack.min.css'`

**Comment by hcivelek** [comment]
@agnivade thank you for tip about css. I tried to achieve for an hour.

**Comment by zerodois** [comment]
Changed. Thanks for your feedback ;)
